feat: add missing fields from dcat-ap-no spec
Informasjonsforvaltning/dataservice-catalog pull request #97
Opened 2021-06-28 11:11 UTC by jeffreiffers

Fixes #88

2021-06-28 11:43 UTC, NilsOveTen approved these changes

2021-06-28 11:43 UTC, NilsOveTen commented on src/main/java/no/fdk/dataservicecatalog/service/DcatApNoModelService.java
> +        if (dataService.getType() != null) {
Ta med isURI, jena er mindre streng på hva som legges til som URIRef enn hva den takler å lese. Så høstingen av katalogen kan feile om et av disse feltene ikke opprettholder uri-kravet.

2021-06-28 11:43 UTC, NilsOveTen commented on src/main/java/no/fdk/dataservicecatalog/service/DcatApNoModelService.java
> +        if (dataService.getAccessRights() != null && dataService.getAccessRights() != null && isURI(dataService.getAccessRights())) {
```suggestion
        if (dataService.getAccessRights() != null && isURI(dataService.getAccessRights())) {
```

2021-06-28 11:43 UTC, NilsOveTen commented on src/main/java/no/fdk/dataservicecatalog/service/DcatApNoModelService.java
> +                    ResourceFactory.createResource(URIref.encode(page))));
`isURI(page)`

2021-06-28 11:43 UTC, NilsOveTen commented on src/main/java/no/fdk/dataservicecatalog/service/DcatApNoModelService.java
> +                    ResourceFactory.createResource(URIref.encode(landingPage))));
`isURI(landingPage)`

2021-06-28 11:43 UTC, NilsOveTen commented on src/main/java/no/fdk/dataservicecatalog/service/DcatApNoModelService.java
> +                    ResourceFactory.createResource(URIref.encode(theme))));
`isURI(theme)`

2021-06-28 11:44 UTC, NilsOveTen requested changes
ref kommentarene når jeg trykket approve

2021-06-29 05:16 UTC, NilsOveTen approved these changes

2021-06-29 14:53 UTC, matsjs approved these changes

2021-07-01 07:18 UTC, matsjs approved these changes

2021-07-07 10:45 UTC, merged